CREATE PROCEDURE InclusaoVendedor 
@MATRICULA AS VARCHAR(5), @NOME AS VARCHAR(100), @PERCENTUAL AS FLOAT,
@DATAADMISSAO AS DATE, @FERIAS AS BIT, @BAIRRO AS VARCHAR(50)
AS
BEGIN
INSERT INTO [TABELA DE VENDEDORES] (MATRICULA, NOME, [PERCENTUAL COMISSÃO], [DATA ADMISSÃO], [DE FERIAS], BAIRRO)
VALUES (@MATRICULA, @NOME, @PERCENTUAL, @DATAADMISSAO, @FERIAS, @BAIRRO)
END

EXEC InclusaoVendedor '00238','Pericles Alves',0.11,'20160821',0,'Santo Amaro'

--Crie uma nova SP chamada InclusaoVendedor01, tratando este erro usando @@ERROR e @@ROWCOUNT.

CREATE PROCEDURE InclusaoVendedor01
	@MATRICULA AS VARCHAR(5),
	@NOME AS VARCHAR(100),
	@PERCENTUAL AS FLOAT,
	@DATAADMISSAO AS DATE,
	@FERIAS AS BIT,
	@BAIRRO AS VARCHAR(50),
	@NUMERRO AS INT OUTPUT,
	@NUMLINHA AS INT OUTPUT
AS
BEGIN
INSERT INTO [TABELA DE VENDEDORES] (MATRICULA, NOME, [PERCENTUAL COMISSÃO], [DATA ADMISSÃO], [DE FERIAS], BAIRRO)
	VALUES (@MATRICULA, @NOME, @PERCENTUAL, @DATAADMISSAO, @FERIAS, @BAIRRO)
	SELECT @NUMERRO = @@ERROR, @NUMLINHA = @@ROWCOUNT
END

DECLARE @NUMERRO INT
DECLARE @NUMLINHA INT
EXEC InclusaoVendedor01 '00238', 'Pericles Alves', 0.11, '20160821', 0, 'Santo Amaro', 
	@NUMERRO = @NUMERRO OUTPUT,
	@NUMLINHA = @NUMLINHA OUTPUT
IF @NUMERRO <> 0
	PRINT 'Houve um erro:' +
		CONVERT(VARCHAR(10), @NUMERRO) + ' - ' + 
        CONVERT(VARCHAR(30), @NUMLINHA)

--Crie uma nova SP chamada InclusaoVendedor02, agora tratando o erro com TRY-CATCH.

CREATE PROCEDURE InclusaoVendedorTRYCATCH
	@MATRICULA AS VARCHAR(5),
	@NOME AS VARCHAR(100),
	@PERCENTUAL AS FLOAT,
	@DATAADMISSAO AS DATE,
	@FERIAS AS BIT,
	@BAIRRO AS VARCHAR(50),
	@MENSAGEM AS VARCHAR (50) OUTPUT
AS
BEGIN TRY
	INSERT INTO [TABELA DE VENDEDORES] (MATRICULA, NOME, [PERCENTUAL COMISSÃO], [DATA ADMISSÃO], [DE FERIAS], BAIRRO)
		VALUES (@MATRICULA, @NOME, @PERCENTUAL, @DATAADMISSAO, @FERIAS, @BAIRRO)
END TRY
BEGIN CATCH
	SET @MENSAGEM = 'Erro ' + CONVERT(VARCHAR(10), @@ERROR) 
END CATCH

DECLARE @MENSAGEM VARCHAR(50)
EXEC InclusaoVendedorTRYCATCH '00238', 'Pericles Alves', 0.11, '20160821', 0, 'Santo Amaro', 
	@MENSAGEM = @MENSAGEM OUTPUT
IF @MENSAGEM <> ''
	PRINT @MENSAGEM

--Crie uma nova SP chamada InclusaoVendedor03, agora tratando o erro com TRY-CATCH, exibindo todas as funções de erro na mensagem.

CREATE PROCEDURE InclusaoVendedorTRYCATCHALL
	@MATRICULA AS VARCHAR(5),
	@NOME AS VARCHAR(100),
	@PERCENTUAL AS FLOAT,
	@DATAADMISSAO AS DATE,
	@FERIAS AS BIT,
	@BAIRRO AS VARCHAR(50),
	@MENSAGEM AS VARCHAR (MAX) OUTPUT
AS
BEGIN TRY
	INSERT INTO [TABELA DE VENDEDORES] (MATRICULA, NOME, [PERCENTUAL COMISSÃO], [DATA ADMISSÃO], [DE FERIAS], BAIRRO)
		VALUES (@MATRICULA, @NOME, @PERCENTUAL, @DATAADMISSAO, @FERIAS, @BAIRRO)
END TRY
BEGIN CATCH
	SET @MENSAGEM = 'Erro: ' + CONVERT(VARCHAR(10), ERROR_NUMBER()) + ' - '
	SET @MENSAGEM = @MENSAGEM + 'Mensagem: ' + ERROR_MESSAGE() + ' - '
	SET @MENSAGEM = @MENSAGEM + 'Severidade: ' + CONVERT(VARCHAR(10), ERROR_SEVERITY()) + ' - '
	SET @MENSAGEM = @MENSAGEM + 'Estado: ' + CONVERT(VARCHAR(10), ERROR_STATE()) + ' - '
	SET @MENSAGEM = @MENSAGEM + 'Linha: ' + CONVERT(VARCHAR(10), ERROR_LINE())
END CATCH

DECLARE @MENSAGEM VARCHAR(MAX)
EXEC InclusaoVendedorTRYCATCHALL '00238', 'Pericles Alves', 0.11, '20160821', 0, 'Santo Amaro', 
	@MENSAGEM = @MENSAGEM OUTPUT
IF @MENSAGEM <> ''
	PRINT @MENSAGEM