
USE SUCOS_VENDAS
SELECT * FROM SYS.database_files

USE SUCOS_VENDAS
ALTER DATABASE SUCOS_VENDAS SET RECOVERY SIMPLE
DBCC SHRINKDATABASE ('SUCOS_VENDAS', NOTRUNCATE)
DBCC SHRINKDATABASE ('SUCOS_VENDAS', TRUNCATEONLY)
ALTER DATABASE SUCOS_VENDAS SET RECOVERY FULL


USE SUCOS_VENDAS
BACKUP DATABASE SUCOS_VENDAS TO DISK = 'E:\Academia\Alura\sql\sql 2019\05 admin\ex\SUCOS_VENDAS.BAK'
BACKUP DATABASE SUCOS_VENDAS TO DISK = 'E:\Academia\Alura\sql\sql 2019\05 admin\ex\SUCOS_VENDAS.BAK' WITH INIT
BACKUP DATABASE SUCOS_VENDAS TO DISK = 'E:\Academia\Alura\sql\sql 2019\05 admin\ex\SUCOS_VENDAS2.BAK' WITH COMPRESSION

EXEC [dbo].CriaNotaFiscal '20180401'

BACKUP LOG SUCOS_VENDAS TO DISK = 'E:\Academia\Alura\sql\sql 2019\05 admin\ex\SUCOS_VENDAS_LOG.BAK'

RESTORE VERIFYONLY FROM DISK = 'E:\Academia\Alura\sql\sql 2019\05 admin\ex\SUCOS_VENDAS.BAK'
RESTORE HEADERONLY FROM DISK = 'E:\Academia\Alura\sql\sql 2019\05 admin\ex\SUCOS_VENDAS.BAK'

ALTER DATABASE SUCOS_VENDAS SET RECOVERY FULL
BACKUP DATABASE SUCOS_VENDAS TO DISK = 'E:\Academia\Alura\sql\sql 2019\05 admin\ex\SUCOS_VENDAS4.BAK' WITH INIT

SELECT * FROM [NOTAS FISCAIS] WHERE DATA = '20180405'
EXEC [dbo].CriaNotaFiscal '20180405'

USE MASTER
ALTER DATABASE SUCOS_VENDAS SET SINGLE_USER WITH ROLLBACK IMMEDIATE
DROP DATABASE SUCOS_VENDAS
RESTORE DATABASE SUCOS_VENDAS FROM DISK = 'E:\Academia\Alura\sql\sql 2019\05 admin\ex\SUCOS_VENDAS4.BAK' WITH RECOVERY

USE SUCOS_VENDAS
SELECT * FROM [NOTAS FISCAIS] WHERE DATA = '20180405'


BACKUP DATABASE SUCOS_VENDAS TO DISK = 'E:\Academia\Alura\sql\sql 2019\05 admin\ex\SUCOS_VENDAS5.BAK' WITH INIT
BACKUP DATABASE SUCOS_VENDAS TO DISK = 'E:\Academia\Alura\sql\sql 2019\05 admin\ex\SUCOS_VENDAS5.BAK'

RESTORE HEADERONLY FROM DISK = 'E:\Academia\Alura\sql\sql 2019\05 admin\ex\SUCOS_VENDAS5.BAK'

USE MASTER
ALTER DATABASE SUCOS_VENDAS SET SINGLE_USER WITH ROLLBACK IMMEDIATE
DROP DATABASE SUCOS_VENDAS

RESTORE DATABASE SUCOS_VENDAS FROM DISK = 'E:\Academia\Alura\sql\sql 2019\05 admin\ex\SUCOS_VENDAS5.BAK'
	WITH FILE = 3, RECOVERY


USE SUCOS_VENDAS
	CREATE TABLE TST_BACKUP (POS INT)
	INSERT INTO TST_BACKUP (POS) VALUES (1)

SELECT * FROM TST_BACKUP

--1:00
BACKUP DATABASE SUCOS_VENDAS TO DISK = 'E:\Academia\Alura\sql\sql 2019\05 admin\ex\SUCOS_VENDAS_COMPLETO.BAK'
	WITH INIT

--4:00
INSERT INTO TST_BACKUP (POS) VALUES (2)
BACKUP LOG SUCOS_VENDAS TO DISK = 'E:\Academia\Alura\sql\sql 2019\05 admin\ex\SUCOS_VENDAS_COMPLETO.BAK'
	WITH NOINIT
--6:00
INSERT INTO TST_BACKUP (POS) VALUES (3)
BACKUP LOG SUCOS_VENDAS TO DISK = 'E:\Academia\Alura\sql\sql 2019\05 admin\ex\SUCOS_VENDAS_COMPLETO.BAK'
	WITH NOINIT
--8:00
INSERT INTO TST_BACKUP (POS) VALUES (4)
BACKUP LOG SUCOS_VENDAS TO DISK = 'E:\Academia\Alura\sql\sql 2019\05 admin\ex\SUCOS_VENDAS_COMPLETO.BAK'
	WITH NOINIT

--9:00 - DIFFERENTIAL
INSERT INTO TST_BACKUP (POS) VALUES (5)
BACKUP DATABASE SUCOS_VENDAS TO DISK = 'E:\Academia\Alura\sql\sql 2019\05 admin\ex\SUCOS_VENDAS_COMPLETO.BAK'
	WITH DIFFERENTIAL

--10:00
INSERT INTO TST_BACKUP (POS) VALUES (6)
BACKUP LOG SUCOS_VENDAS TO DISK = 'E:\Academia\Alura\sql\sql 2019\05 admin\ex\SUCOS_VENDAS_COMPLETO.BAK'
	WITH NOINIT
--12:00
INSERT INTO TST_BACKUP (POS) VALUES (7)
BACKUP LOG SUCOS_VENDAS TO DISK = 'E:\Academia\Alura\sql\sql 2019\05 admin\ex\SUCOS_VENDAS_COMPLETO.BAK'
	WITH NOINIT
--14:00
INSERT INTO TST_BACKUP (POS) VALUES (8)
BACKUP LOG SUCOS_VENDAS TO DISK = 'E:\Academia\Alura\sql\sql 2019\05 admin\ex\SUCOS_VENDAS_COMPLETO.BAK'
	WITH NOINIT

--14:00 - DIFFERENTIAL
INSERT INTO TST_BACKUP (POS) VALUES (9)
BACKUP DATABASE SUCOS_VENDAS TO DISK = 'E:\Academia\Alura\sql\sql 2019\05 admin\ex\SUCOS_VENDAS_COMPLETO.BAK'
	WITH DIFFERENTIAL

--15:00
INSERT INTO TST_BACKUP (POS) VALUES (10)
BACKUP LOG SUCOS_VENDAS TO DISK = 'E:\Academia\Alura\sql\sql 2019\05 admin\ex\SUCOS_VENDAS_COMPLETO.BAK'
	WITH NOINIT
--17:00
INSERT INTO TST_BACKUP (POS) VALUES (11)
BACKUP LOG SUCOS_VENDAS TO DISK = 'E:\Academia\Alura\sql\sql 2019\05 admin\ex\SUCOS_VENDAS_COMPLETO.BAK'
	WITH NOINIT
--19:00
INSERT INTO TST_BACKUP (POS) VALUES (12)
BACKUP LOG SUCOS_VENDAS TO DISK = 'E:\Academia\Alura\sql\sql 2019\05 admin\ex\SUCOS_VENDAS_COMPLETO.BAK'
	WITH NOINIT
--21:00
INSERT INTO TST_BACKUP (POS) VALUES (13)
BACKUP LOG SUCOS_VENDAS TO DISK = 'E:\Academia\Alura\sql\sql 2019\05 admin\ex\SUCOS_VENDAS_COMPLETO.BAK'
	WITH NOINIT

SELECT * FROM TST_BACKUP
RESTORE HEADERONLY FROM DISK = 'E:\Academia\Alura\sql\sql 2019\05 admin\ex\SUCOS_VENDAS_COMPLETO.BAK'

--RECOVERING DATA BEFORE 17:30
USE MASTER
ALTER DATABASE SUCOS_VENDAS SET SINGLE_USER WITH ROLLBACK IMMEDIATE
DROP DATABASE SUCOS_VENDAS

--1:00 FULL INITIAL (1)
RESTORE DATABASE SUCOS_VENDAS FROM DISK = 'E:\Academia\Alura\sql\sql 2019\05 admin\ex\SUCOS_VENDAS_COMPLETO.BAK'
	WITH FILE = 1, NORECOVERY
--14:00 DIFFERENTIAL (9)
RESTORE DATABASE SUCOS_VENDAS FROM DISK = 'E:\Academia\Alura\sql\sql 2019\05 admin\ex\SUCOS_VENDAS_COMPLETO.BAK'
	WITH FILE = 9, NORECOVERY
--15:00 LOG (10)
RESTORE DATABASE SUCOS_VENDAS FROM DISK = 'E:\Academia\Alura\sql\sql 2019\05 admin\ex\SUCOS_VENDAS_COMPLETO.BAK'
	WITH FILE = 10, NORECOVERY
--17:00 LOG (11)
RESTORE DATABASE SUCOS_VENDAS FROM DISK = 'E:\Academia\Alura\sql\sql 2019\05 admin\ex\SUCOS_VENDAS_COMPLETO.BAK'
	WITH FILE = 11, RECOVERY

USE SUCOS_VENDAS
SELECT * FROM TST_BACKUP